# masterauth作用：主要是針對master對應的slave節點設置的，在slave節點數據同步的時候用到。
# requirepass作用：對登錄權限做限制，redis每個節點的requirepass可以是獨立、不同的。
# 每個 redis node 都需要開放兩個 TCP port：一個是 redis client 連線使用的 port (常見為 6379) 另一個是 cluster bus 用來做 node 間的交互溝通 (固定為 client port 加上 10000)
version: '3.4'
services:
  redis-node1:
    image: redis:7.2
    environment:
      ip: $ip
      Requirepass: $Requirepass
      Masterauth: $Masterauth
    volumes:
    - ./redis.conf:/usr/local/etc/redis/redis.conf
    - ./data/redis-node1/data:/data
    ports: 
      - 7000:7000 
      - 17000:17000 
    entrypoint: [redis-server, /usr/local/etc/redis/redis.conf, --port,"7000", --cluster-announce-ip,"${ip}", --requirepass,"${Requirepass}", --masterauth,"${Masterauth}"]

  redis-node2:
    image: redis:7.2
    environment:
      ip: $ip
      Requirepass: $Requirepass
      Masterauth: $Masterauth
    volumes:
    - ./redis.conf:/usr/local/etc/redis/redis.conf
    - ./data/redis-node2/data:/data
    ports: 
      - 7001:7001 
      - 17001:17001 
    entrypoint: [redis-server, /usr/local/etc/redis/redis.conf, --port,"7001", --cluster-announce-ip,"${ip}", --requirepass,"${Requirepass}", --masterauth,"${Masterauth}"]

  redis-node3:
    image: redis:7.2
    environment:
      ip: $ip
      Requirepass: $Requirepass
      Masterauth: $Masterauth
    volumes:
    - ./redis.conf:/usr/local/etc/redis/redis.conf
    - ./data/redis-node3/data:/data
    ports: 
      - 7002:7002 
      - 17002:17002 
    entrypoint: [redis-server, /usr/local/etc/redis/redis.conf, --port,"7002", --cluster-announce-ip,"${ip}", --requirepass,"${Requirepass}", --masterauth,"${Masterauth}"]

  redis-node4:
    image: redis:7.2
    environment:
      ip: $ip
      Requirepass: $Requirepass
      Masterauth: $Masterauth
    volumes:
    - ./redis.conf:/usr/local/etc/redis/redis.conf
    - ./data/redis-node4/data:/data
    ports: 
      - 7003:7003 
      - 17003:17003 
    entrypoint: [redis-server, /usr/local/etc/redis/redis.conf, --port,"7003", --cluster-announce-ip,"${ip}", --requirepass,"${Requirepass}", --masterauth,"${Masterauth}"]

  redis-node5:
    image: redis:7.2
    environment:
      ip: $ip
      Requirepass: $Requirepass
      Masterauth: $Masterauth
    volumes:
    - ./redis.conf:/usr/local/etc/redis/redis.conf
    - ./data/redis-node5/data:/data
    ports: 
      - 7004:7004 
      - 17004:17004 
    entrypoint: [redis-server, /usr/local/etc/redis/redis.conf, --port,"7004", --cluster-announce-ip,"${ip}", --requirepass,"${Requirepass}", --masterauth,"${Masterauth}"]

  redis-node6:
    image: redis:7.2
    environment:
      ip: $ip
      Requirepass: $Requirepass
      Masterauth: $Masterauth
    volumes:
    - ./redis.conf:/usr/local/etc/redis/redis.conf
    - ./data/redis-node6/data:/data
    ports: 
      - 7005:7005 
      - 17005:17005 
    entrypoint: [redis-server, /usr/local/etc/redis/redis.conf, --port,"7005", --cluster-announce-ip,"${ip}", --requirepass,"${Requirepass}", --masterauth,"${Masterauth}"]

  redis-cluster-creator:
    image: redis:7.2
    environment:
      ip: $ip
      Requirepass: $Requirepass
      Masterauth: $Masterauth
    entrypoint: [/bin/sh,-c,'echo "yes" | redis-cli -a ${Requirepass} --cluster create ${ip}:7000 ${ip}:7001 ${ip}:7002 ${ip}:7003 ${ip}:7004 ${ip}:7005 --cluster-replicas 1'] 
    depends_on: 
      - redis-node1 
      - redis-node2
      - redis-node3 
      - redis-node4
      - redis-node5 
      - redis-node6

  init-data:
    image: busybox
    volumes:
      - ./data/redisinsight:/data
    command: ["sh", "-c", "chown 1001:1001 /data"]
    restart: 'no'
    depends_on:
      - redis-cluster-creator

  redisinsight:
    image: redislabs/redisinsight:1.14.0
    volumes:
    - ./data/redisinsight:/db
    ports:
      - 8001:8001
    depends_on:
      - init-data






